### ISSUE TITLE
Bug/Crash when referencing a plugin that doesn't exists

### ISSUE THREAD

**Issue by buixor** [crowdsecurity/crowdsec#1250]
Having a profiles.yaml that is referencing a plugin that doesn't exist (ie. notification-mail binary is missing), triggering this profile will crash crowdsec :

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xdf258c]

goroutine 180 [running]:
github.com/crowdsecurity/crowdsec/pkg/csplugin.(*PluginBroker).pushNotificationsToPlugin(0x2444440, {0xc0006e6290, 0x18151c0}, {0xc000df8600, 0x0, 0x1})
	/codebuild/output/src772/src/s3/01/pkg/csplugin/broker.go:291 +0x3cc
github.com/crowdsecurity/crowdsec/pkg/csplugin.(*PluginBroker).Run.func1()
	/codebuild/output/src772/src/s3/01/pkg/csplugin/broker.go:116 +0x3f
created by github.com/crowdsecurity/crowdsec/pkg/csplugin.(*PluginBroker).Run
	/codebuild/output/src772/src/s3/01/pkg/csplugin/broker.go:115 +0x2da

```

**Comment by buixor** [comment]
fixed by #1251
