### ISSUE TITLE
Cloudflare Bouncer runtime error

### ISSUE THREAD

**Issue by barendbotes** [crowdsecurity/crowdsec#1263]
cloudflare-bouncer gets the following error

```
panic: runtime error: invalid memory address or nil pointer dereference,
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xa3dfb5],
,
goroutine 20 [running]:,
main.(*CloudflareWorker).UpdateIPLists(0xc000082780, 0x0, 0x0),
	/go/src/cs-cloudflare-bouncer/cloudflare.go:445 +0x5b5,
main.(*CloudflareWorker).runProcessorOnDecisions(0xc000082780, 0xc000795f10, 0xc000c0c000, 0x2afd, 0x3000),
	/go/src/cs-cloudflare-bouncer/cloudflare.go:862 +0xd3,
main.(*CloudflareWorker).Run(0xc000082780, 0x0, 0x0),
	/go/src/cs-cloudflare-bouncer/cloudflare.go:887 +0x2dc,
main.main.func3(0x0, 0x0),
	/go/src/cs-cloudflare-bouncer/main.go:277 +0x2a,
gopkg.in/tomb%2ev2.(*Tomb).run(0xc0000b6050, 0xc00009f1b0),
	/go/pkg/mod/gopkg.in/tomb.v2@v2.0.0-20161208151619-d5d1b5820637/tomb.go:163 +0x38,
created by gopkg.in/tomb%2ev2.(*Tomb).Go,
	/go/pkg/mod/gopkg.in/tomb.v2@v2.0.0-20161208151619-d5d1b5820637/tomb.go:159 +0xbc
```

I have crowdsec installed on docker, parsing traefik logs. All worked well using the traefik bouncer, but I decided to try and use the cloudflare bouncer since I have my domains on cloudflare free plan.

I set up all the permissions on Cloudflare and can see that the firewall rules and ip lists are being created by crowdsec, but after a while I get the above error.

**Comment by barendbotes** [comment]
Hi, I should've raised this on the bouncer github, but I installed it on
docker, with the crowdsec itself. I followed the documentation.

Kind Regards


Barend Botes
BotesNetworks

*e:* ***@***.*** ***@***.***>
*m:* +27 71 303 1048 <+27713031048>

**Comment by sabban** [comment]
if it happens please report against https://github.com/crowdsecurity/cs-cloudflare-bouncer
