### ISSUE TITLE
Bug/Installation errors on Debian 11

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [crowdsecurity/crowdsec#1487]
**Describe the bug**
I get an error message during installation.

**To Reproduce**
```
$ curl -s https://packagecloud.io/install/repositories/crowdsec/crowdsec/script.deb.sh | sudo bash
Detected operating system as debian/bullseye.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing debian-archive-keyring which is needed for installing
apt-transport-https on many Debian systems.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/crowdsec_crowdsec.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.

The repository is setup! You can now install packages

$ sudo apt-get update
Hit:1 https://security.debian.org/debian-security bullseye-security InRelease
Hit:2 https://deb.debian.org/debian bullseye InRelease
Hit:3 https://deb.debian.org/debian bullseye-updates InRelease
Hit:4 https://packagecloud.io/crowdsec/crowdsec/debian bullseye InRelease
Reading package lists... Done

$ sudo apt-get install crowdsec
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  crowdsec
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/27.1 MB of archives.
After this operation, 102 MB of additional disk space will be used.
Preconfiguring packages ...
Selecting previously unselected package crowdsec.
(Reading database ... 41289 files and directories currently installed.)
Preparing to unpack .../crowdsec_1.3.3_amd64.deb ...
You can always run the configuration again interactively by using '/usr/share/crowdsec/wizard.sh -c
Unpacking crowdsec (1.3.3) ...
Setting up crowdsec (1.3.3) ...
Creating /etc/crowdsec/acquis.yaml
INFO[04/28/2022:12:58:37 AM] crowdsec_wizard: service 'sshd': /var/log/auth.log
INFO[04/28/2022:12:58:37 AM] crowdsec_wizard: service 'linux': /var/log/syslog /var/log/kern.log /var/log/messages
WARN[28-04-2022 12:58:37 AM] can't load CAPI credentials from '/etc/crowdsec/online_api_credentials.yaml' (missing field)
INFO[28-04-2022 12:58:37 AM] push and pull to Central API disabled
panic: runtime error: slice bounds out of range [:32] with length 0

goroutine 1 [running]:
main.generateID({0x0, 0x0})
        /codebuild/output/src568/src/s3/01/cmd/crowdsec-cli/machines.go:90 +0xa7
main.NewMachinesCmd.func5(0xc00038b400, {0xc00015d000, 0x1, 0x1})
        /codebuild/output/src568/src/s3/01/cmd/crowdsec-cli/machines.go:216 +0x58
github.com/spf13/cobra.(*Command).execute(0xc00038b400, {0xc00015cff0, 0x1, 0x1})
        /codebuild/output/src568/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0xc000216500)
        /codebuild/output/src568/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /codebuild/output/src568/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
        /codebuild/output/src568/src/s3/01/cmd/crowdsec-cli/main.go:184 +0xadd
dpkg: error processing package crowdsec (--configure):
 installed crowdsec package post-installation script subprocess returned error exit status 2
Errors were encountered while processing:
 crowdsec
E: Sub-process /usr/bin/dpkg returned an error code (1)

$ sudo apt purge crowdsec
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be REMOVED:
  crowdsec*
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 102 MB disk space will be freed.
Do you want to continue? [Y/n]
(Reading database ... 41340 files and directories currently installed.)
Removing crowdsec (1.3.3) ...
FATA[28-04-2022 01:01:52 AM] Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
(Reading database ... 41325 files and directories currently installed.)
Purging configuration files for crowdsec (1.3.3) ...
```

**Expected behavior**
I expected it to work.

**Technical Information (please complete the following information):**
uname -a:
`Linux hostname 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux`

lsb_release -a:
```
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

**Comment by blotus** [comment]
Hello,

Could you confirm that either of `/var/lib/dbus/machine-id` or `/etc/machine-id` exist and are non-empty ?

Are you using a stock bullseye or something else that is based on bullseye ?

**Comment by AlyoshaVasilieva** [comment]
`/var/lib/dbus/machine-id` exists but is empty, `/etc/machine-id` exists and has content (32 chars hex)

As far as I know it's stock bullseye.

**Comment by AlyoshaVasilieva** [comment]
Based on that PR's reason I ran `dbus-uuidgen --ensure` which fixed `/var/lib/dbus/machine-id` and now install works.

**Comment by buixor** [comment]
and it's out :smiley:
