### ISSUE TITLE
Cannot Install crowdsec

### ISSUE THREAD

**Issue by Compr0mzd** [crowdsecurity/crowdsec#1532]
After adding the repo on Debian 11 with latest updates and installing crowdsec package during the installation I came across this error : 
`Setting up crowdsec (1.3.4) ...
Creating /etc/crowdsec/acquis.yaml
INFO[05/17/2022:10:09:49 AM] crowdsec_wizard: service 'sshd': /var/log/auth.log
INFO[05/17/2022:10:09:49 AM] crowdsec_wizard: service 'linux': /var/log/syslog /var/log/kern.log /var/log/messages
WARN[17-05-2022 10:09:49 AM] can't load CAPI credentials from '/etc/crowdsec/online_api_credentials.yaml' (missing field)
INFO[17-05-2022 10:09:49 AM] push and pull to Central API disabled
panic: runtime error: slice bounds out of range [:32] with length 0

goroutine 1 [running]:
main.generateID({0x0, 0x0})
        /codebuild/output/src020/src/s3/01/cmd/crowdsec-cli/machines.go:90 +0xa7
main.NewMachinesCmd.func5(0xc000383180, {0xc0004056c0, 0x1, 0x1})
        /codebuild/output/src020/src/s3/01/cmd/crowdsec-cli/machines.go:216 +0x58
github.com/spf13/cobra.(*Command).execute(0xc000383180, {0xc0004056b0, 0x1, 0x1})
        /codebuild/output/src020/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0xc000310c80)
        /codebuild/output/src020/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /codebuild/output/src020/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
        /codebuild/output/src020/src/s3/01/cmd/crowdsec-cli/main.go:184 +0xadd
dpkg: error processing package crowdsec (--configure):
 installed crowdsec package post-installation script subprocess returned error exit status 2
Errors were encountered while processing:
 crowdsec
E: Sub-process /usr/bin/dpkg returned an error code (1)
`
Any idea how I can fix this ?

**Comment by Compr0mzd** [comment]
I did generate the dbus-uuidgen --ensure it worked installing the agent but after start i got this error
level=fatal msg="missing local API credentials for crowdsec agent, abort"

**Comment by AlteredCoder** [comment]
Hello, now that you have run  `dbus-uuidgen --ensure` you need to run `cscli machines add -a` or to reinstall crowdsec before starting the service

**Comment by blotus** [comment]
I'm closing this as the root cause is fixed and will be part of 1.4.0.
