### ISSUE TITLE
cscli support dump not working in k8s

### ISSUE THREAD

**Issue by mmetc** [crowdsecurity/crowdsec#1972]
### What happened?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1191f93]

goroutine 1 [running]:
main.NewSupportCmd.func2(0xc0003fe780?, {0xc0001205e0?, 0x2?, 0x2?})
	/go/src/crowdsec/cmd/crowdsec-cli/support.go:312 +0x8f3
github.com/spf13/cobra.(*Command).execute(0xc0003fe780, {0xc0001205c0, 0x2, 0x2})
	/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001dd400)
	/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
	/go/src/crowdsec/cmd/crowdsec-cli/main.go:230 +0xbf6
```

### What did you expect to happen?

it should create the zip file

### How can we reproduce it (as minimally and precisely as possible)?

Install the helm chart, run "cscli support dump". Could not reproduce with Docker alone.

### Crowdsec version

1.4.4

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Enabled collections and parsers

<details>

```console
$ cscli hub list -o raw
# paste output here
```

</details>

### Acquisition config

<details>
```console
# On Linux:
$ cat /etc/crowdsec/acquis.yaml /etc/crowdsec/acquis.d/*
# paste output here

# On Windows:
C:\> Get-Content C:\ProgramData\CrowdSec\config\acquis.yaml
# paste output here
</details>


### Config show

<details>

```console
$ cscli config show
# paste output here
```

</details>

### Prometheus metrics

<details>

```console
$ cscli metrics
# paste output here
```

</details>

### Related custom configs versions (if applicable) : notification plugins, custom scenarios, parsers etc.

<details>

</details>

**Comment by LaurenceJJones** [comment]
Most likely it because you have 2 pods one for agent another for lapi. They both hold different information that the support dump gathers.

**Comment by mmetc** [comment]
this works after the "cscli support" rewrite - tested with 1.6.4
